language: php
dist: trusty
sudo: false

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SYMFONY_VERSION="3.4.*"
        - php: 7.2
          env: SYMFONY_VERSION="4.0.*"
        - php: 7.2
          env: SYMFONY_VERSION="4.1.*"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update
    - composer require --no-update symfony/framework-bundle=$SYMFONY_VERSION
    - composer require --no-update --dev symfony/form=$SYMFONY_VERSION symfony/twig-bundle=$SYMFONY_VERSION
    - composer install

script:
    - php vendor/bin/phpunit
